#!/usr/bin/php
<?php



// (Getting the values)
$cli_user  = get_current_user();
$http_user = 'www-data';



// (Setting the value)
$basedir = '/var/www/siteman';

// (Executing the commands)
system( 'sudo mkdir -p ' . escapeshellarg( $basedir ) );
system( "sudo chown $cli_user:$http_user " . escapeshellarg( $basedir ) );
system( "sudo chmod 755 " . escapeshellarg( $basedir ) );



if ( count( $argv ) === 1 )
{// (Command is without arguments)
    // Printing the value
    echo <<<EOD

    Site Manager Command Line Tool (siteman)

    Usage
        siteman add {fqdn}                             Adding a new site
        siteman del {fqdn}                             Deleting a site

        siteman config {fqdn}                          Configuring a site
        siteman cert {fqdn}                            Creating a CA-signed certificate for the site

        siteman list ?{filter=ENABLED|DISABLED}        Listing all sites


    EOD
    ;

    // (Closing the process)
    exit;
}



switch ( $argv[1] )
{
    case 'add':
        if ( !isset( $argv[2] ) ) exit;



        // (Getting the value)
        $fqdn = $argv[2];



        // (Getting the value)
        $site_path = "$basedir/$fqdn";

        if ( is_dir( $site_path ) )
        {// (Directory found)
            if ( readline( "Directory '$site_path' already exists. Are you sure to overwrite this ? [Y/n]\n" ) !== 'Y' )
            {// (Confirmation is failed)
                // Printing the value
                echo "\n\nDirectory '$site_path' has not been changed\n\n\n";

                // Closing the process
                exit;
            }



            // (Executing the command)
            system( "sudo rm -rf " . escapeshellarg( $site_path ) );

            // Printing the value
            echo "\n\nDirectory '$site_path' has been deleted\n\n\n";
        }



        // (Executing the commands)
        system( "sudo mkdir -p " . escapeshellarg( $site_path ) );
        system( "sudo chown -R $cli_user:$http_user " . escapeshellarg( $site_path ) );
        system( "sudo chmod 2755 " . escapeshellarg( $site_path ) );



        foreach ( [ 'apache/log', 'apache/cert', 'web' ] as $dir )
        {// Processing each entry
            // (Executing the command)
            system( 'sudo mkdir -p ' . escapeshellarg( "$site_path/$dir" ) );
        }



        // (Executing the command)
        system( "sudo echo \"<?php echo '<pre>SiteMAN :: Welcome to site <b>$fqdn</b> !</pre>' ?>\" > " . escapeshellarg( "$site_path/web/index.php" ) );



        // (Executing the command)
        system( "sudo chown -R $cli_user:$http_user " . escapeshellarg( "$site_path" ) );



        /*

        // (Getting the values)
        $vfp_user  = posix_getpwuid( fileowner( $path ) )['name'];
        $vfp_group = posix_getpwuid( filegroup( $path ) )['name'];

        // (Executing the cmd)
        system("sudo chown -R $vfp_user:$vfp_group " . escapeshellarg( $site_path ) );

        */



        // (Getting the value)
        $config_file_path = "/etc/apache2/sites-available/$fqdn.conf";

        if ( file_exists( $config_file_path ) )
        {// (Directory found)
            if ( readline( "File '$config_file_path' already exists. Are you sure to overwrite this ? [Y/n]\n" ) !== 'Y' )
            {// (Confirmation is failed)
                // Printing the value
                echo "\n\nFile '$config_file_path' has not been changed\n\n\n";

                // Closing the process
                exit;
            }
        }



        // (Executing the commands)
        system( "sudo touch " . escapeshellarg( $config_file_path ) );
        system( "sudo chown $cli_user " . escapeshellarg( $config_file_path ) );
        system( "sudo chmod 644 " . escapeshellarg( $config_file_path ) );



        // (Getting the value)
        $config_content = 
            <<<EOD
            <VirtualHost *:80>
                ServerName $fqdn
                #ServerAlias $fqdn
                ServerAdmin info@$fqdn

                DocumentRoot $site_path/web

                ErrorLog $site_path/apache/log/error.log
                CustomLog $site_path/apache/log/access.log combined

                RewriteEngine on
                RewriteCond %{SERVER_NAME} =$fqdn
                RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
            </VirtualHost>



            # VirtualHost for HTTPS
            #<VirtualHost *:443>
            #    ServerName $fqdn
            #    #ServerAlias $fqdn
            #    ServerAdmin info@$fqdn
            #
            #    DocumentRoot $site_path/web
            #
            #    ErrorLog $site_path/apache/log/error.log
            #    CustomLog $site_path/apache/log/access.log combined
            #
            #    SSLEngine on
            #
            #    #Protocols h2 http/1.1
            #
            #
            #
            #    # ReverseProxy
            #    #ProxyPreserveHost On
            #    #ProxyPass / http://127.0.0.1:8090/
            #    #ProxyPassReverse / http://127.0.0.1:8090/
            #    #RequestHeader set X-Forwarded-Proto "https"
            #    #RequestHeader set X-Forwarded-Port "443"
            #
            #
            #
            #    # CA-signed cert (LetsEncrypt)
            #    #Include /etc/letsencrypt/options-ssl-apache.conf
            #    #SSLCertificateFile /etc/letsencrypt/live/$fqdn/fullchain.pem
            #    #SSLCertificateKeyFile /etc/letsencrypt/live/$fqdn/privkey.pem
            #
            #
            #
            #    # SELF-signed cert
            #    #SSLCertificateFile $site_path/apache/cert/cert.pem
            #    #SSLCertificateKeyFile $site_path/apache/cert/key.pem
            #</VirtualHost>
            EOD
        ;

        if ( file_put_contents( $config_file_path, $config_content ) === false )
        {// (Unable to write to the file)
            // (Getting the value)
            $message = "Unable to write to the file '$config_file_path'";

            // Throwing an exception
            throw new \Exception( $message );

            // Closing the process
            exit;
        }



        // (Executing the commands)
        system( "sudo a2dissite " . escapeshellarg( $fqdn ) );
        system( "sudo a2ensite " . escapeshellarg( $fqdn ) );

        system( 'sudo a2enmod ssl' );
        system( 'sudo a2enmod rewrite' );
        system( 'sudo a2enmod headers' );
        system( 'sudo a2enmod http2' );

        system( 'sudo service apache2 restart' );
        system( 'sudo apachectl --config-test' );



        if ( trim( shell_exec("dig +short " . escapeshellarg( $fqdn ) ) ) !== '127.0.0.1' )
        {// (FQDN has been resolved)
            if ( readline( "Do you want to create a CA signed certificate for the fqdn '$fqdn' ? [Y/n]\n" ) === 'Y' )
            {// (Confirmation is ok)
                // (Executing the command)
                system( 'sudo certbot --apache -d ' . escapeshellarg( $fqdn ) . ' > `tty`' );
                #system( "sudo certbot certonly --apache -d \"$fqdn\"" );



                // (Getting the value)
                $lines = explode( "\n", $config_content );

                foreach ( $lines as $i => $line )
                {// Processing each entry
                    if ( $line === '# VirtualHost for HTTPS' )
                    {// Match OK
                        // (Getting the value)
                        $target_line = $i;
                    }

                    if ( !$target_line ) continue;

                    if ( $i > $target_line )
                    {// (Line is after target line
                        // (Getting the value)
                        $lines[$i] = preg_replace( '/^#/', '', $line );
                    }
                }

                foreach ( $lines as $i => $line )
                {// Processing each entry
                    if ( $i <= $target_line ) continue;

                    if ( trim( $line ) === '# CA-signed cert (LetsEncrypt)' )
                    {// Match OK
                        // (Getting the value)
                        $target_line_cert = $i;
                    }

                    if ( !$target_line_cert ) continue;

                    if ( $i > $target_line_cert )
                    {// (Line is after target line)
                        // (Getting the value)
                        $lines[$i] = preg_replace( '/^(\s+)#/', '$1', $line );



                        if ( trim( $line ) === '' ) break;
                    }
                }



                // (Getting the value)
                $config_content = implode( "\n", $lines );

                if ( file_put_contents( $config_file_path, $config_content ) === false )
                {// (Unable to write to the file)
                    // (Getting the value)
                    $message = "Unable to write to the file '$config_file_path'";

                    // Throwing an exception
                    throw new \Exception( $message );

                    // Closing the process
                    exit;
                }


                // (Executing the command)
                system( 'sudo service apache2 restart' );
            }
        }



        // Printing the value
        echo "\nVirtualHost '$fqdn' has been created on the Web Server !\n\n";
    break;

    case 'del':
        if ( !isset( $argv[2] ) ) exit;



        // (Getting the value)
        $fqdn = $argv[2];



        // (Getting the value)
        $site_path = "$basedir/$fqdn";

        if ( is_dir( $site_path ) )
        {// (Directory found)
            if ( readline( "Are you sure to remove the directory '$site_path' ? [Y/n]\n" ) !== 'Y' )
            {// (Confirmation is failed)
                // Printing the value
                echo "\n\nFolder '$site_path' has not been changed\n\n\n";

                // Closing the process
                exit;
            }



            // (Executing the command)
            system( 'sudo rm -rf ' . escapeshellarg( $site_path ) );
        }



        // (Getting the value)
        $config_path = "/etc/apache2/sites-available/$fqdn.conf";

        if ( file_exists( $config_path ) )
        {// (Directory found)
            if ( readline( "Are you sure to remove the file '$config_path' ? [Y/n]\n" ) !== 'Y' )
            {// (Confirmation is failed)
                // Printing the value
                echo "\nFile '$config_path' has not been changed\n\n";

                // Closing the process
                exit;
            }



            // (Executing the commands)
            system( 'sudo a2dissite ' . escapeshellarg( $fqdn ) );
            system( 'sudo rm -rf ' . escapeshellarg( $config_path ) );
        }



        // (Executing the command)
        system( 'sudo service apache2 restart' );



        // Printing the value
        echo "\nVirtualHost '$fqdn' has been deleted from Web Server !\n\n";
    break;

    case 'config':
        if ( !isset( $argv[2] ) ) exit;



        // (Getting the value)
        $fqdn = $argv[2];



        // (Executing the command)
        system( "sudo nano \"/etc/apache2/sites-available/$fqdn.conf\" > `tty`" );
    break;

    case 'cert':
        if ( !isset( $argv[2] ) ) exit;



        // (Getting the value)
        $fqdn = $argv[2];



        // (Executing the command)
        system( "sudo certbot --apache -d $fqdn > `tty`" );
    break;

    case 'list':
        // (Getting the value)
        $state_filter = isset( $argv[3] ) ? $argv[3] : false;



        // (Setting the value)
        $results = [];



        // (Getting the value)
        $sites = scandir( '/etc/apache2/sites-available' );

        foreach ( $sites as $fqdn )
        {// Processing each entry
            if ( $fqdn === '.' || $fqdn === '..' ) continue;



            // (Getting the value)
            $state = file_exists( "/etc/apache2/sites-enabled/$fqdn" ) ? 'ENABLED' : 'DISABLED';

            if ( $state_filter && $state_filter !== $state ) continue;



            // (Getting the value)
            $results[ $fqdn ] = $state;
        }



        // Printing the value
        echo preg_replace( '/^Array\s+/', '', print_r( $results, true ) );
    break;
}



?>